/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HealthPayloadApiResponse"];
                        "application/json": components["schemas"]["HealthPayloadApiResponse"];
                        "text/json": components["schemas"]["HealthPayloadApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string | null;
            message: string | null;
            field?: string | null;
        };
        HealthPayload: {
            service: string | null;
            environment: string | null;
            /** Format: date-time */
            utcNow: string;
        };
        HealthPayloadApiResponse: {
            success?: boolean;
            data?: components["schemas"]["HealthPayload"];
            message?: string | null;
            errors?: components["schemas"]["ApiError"][] | null;
            traceId?: string | null;
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
